#import <Foundation/Foundation.h>
#import "NSDate+Core.h"

@interface NSDate (CoreMixcode)
+ (void)currentCalendarMixcode:(NSString *)mixcode;
+ (void)convertDateToLocalTime: (NSDate *)forDate mixcode:(NSString *)mixcode;
+ (void)dateWithDaysFromNow: (NSInteger) days mixcode:(NSString *)mixcode;
+ (void)dateWithDaysBeforeNow: (NSInteger) days mixcode:(NSString *)mixcode;
+ (void)dateWithHoursFromNow: (NSInteger) dHours mixcode:(NSString *)mixcode;
+ (void)dateWithHoursBeforeNow: (NSInteger) dHours mixcode:(NSString *)mixcode;
+ (void)dateWithMinutesFromNow: (NSInteger) dMinutes mixcode:(NSString *)mixcode;
+ (void)dateWithMinutesBeforeNow: (NSInteger) dMinutes mixcode:(NSString *)mixcode;
+ (void)dateTomorrowMixcode:(NSString *)mixcode;
+ (void)dateYesterdayMixcode:(NSString *)mixcode;
+ (void)dateNowMixcode:(NSString *)mixcode;
- (void)stringWithFormat: (NSString *) format mixcode:(NSString *)mixcode;
- (void)stringWithDateStyle: (NSDateFormatterStyle) dateStyle timeStyle: (NSDateFormatterStyle) timeStyle mixcode:(NSString *)mixcode;
- (void)shortStringMixcode:(NSString *)mixcode;
- (void)shortTimeStringMixcode:(NSString *)mixcode;
- (void)shortDateStringMixcode:(NSString *)mixcode;
- (void)mediumStringMixcode:(NSString *)mixcode;
- (void)mediumTimeStringMixcode:(NSString *)mixcode;
- (void)mediumDateStringMixcode:(NSString *)mixcode;
- (void)longStringMixcode:(NSString *)mixcode;
- (void)longTimeStringMixcode:(NSString *)mixcode;
- (void)longDateStringMixcode:(NSString *)mixcode;
- (void)isEqualToDateIgnoringTime: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)isTodayMixcode:(NSString *)mixcode;
- (void)isTomorrowMixcode:(NSString *)mixcode;
- (void)isYesterdayMixcode:(NSString *)mixcode;
- (void)isSameWeekAsDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)isThisWeekMixcode:(NSString *)mixcode;
- (void)isNextWeekMixcode:(NSString *)mixcode;
- (void)isLastWeekMixcode:(NSString *)mixcode;
- (void)isSameMonthAsDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)isThisMonthMixcode:(NSString *)mixcode;
- (void)isLastMonthMixcode:(NSString *)mixcode;
- (void)isNextMonthMixcode:(NSString *)mixcode;
- (void)isSameYearAsDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)isThisYearMixcode:(NSString *)mixcode;
- (void)isNextYearMixcode:(NSString *)mixcode;
- (void)isLastYearMixcode:(NSString *)mixcode;
- (void)isEarlierThanDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)isLaterThanDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)isInFutureMixcode:(NSString *)mixcode;
- (void)isInPastMixcode:(NSString *)mixcode;
- (void)isTypicallyWeekendMixcode:(NSString *)mixcode;
- (void)isTypicallyWorkdayMixcode:(NSString *)mixcode;
- (void)dateByAddingYears: (NSInteger) dYears mixcode:(NSString *)mixcode;
- (void)dateBySubtractingYears: (NSInteger) dYears mixcode:(NSString *)mixcode;
- (void)dateByAddingMonths: (NSInteger) dMonths mixcode:(NSString *)mixcode;
- (void)dateBySubtractingMonths: (NSInteger) dMonths mixcode:(NSString *)mixcode;
- (void)dateByAddingDays: (NSInteger) dDays mixcode:(NSString *)mixcode;
- (void)dateBySubtractingDays: (NSInteger) dDays mixcode:(NSString *)mixcode;
- (void)dateByAddingHours: (NSInteger) dHours mixcode:(NSString *)mixcode;
- (void)dateBySubtractingHours: (NSInteger) dHours mixcode:(NSString *)mixcode;
- (void)dateByAddingMinutes: (NSInteger) dMinutes mixcode:(NSString *)mixcode;
- (void)dateBySubtractingMinutes: (NSInteger) dMinutes mixcode:(NSString *)mixcode;
- (void)componentsWithOffsetFromDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)dateAtStartOfDayMixcode:(NSString *)mixcode;
- (void)dateAtEndOfDayMixcode:(NSString *)mixcode;
- (void)minutesAfterDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)minutesBeforeDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)hoursAfterDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)hoursBeforeDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)daysAfterDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)daysBeforeDate: (NSDate *) aDate mixcode:(NSString *)mixcode;
- (void)distanceInDaysToDate:(NSDate *)anotherDate mixcode:(NSString *)mixcode;
- (void)nearestHourMixcode:(NSString *)mixcode;
- (void)hourMixcode:(NSString *)mixcode;
- (void)minuteMixcode:(NSString *)mixcode;
- (void)secondsMixcode:(NSString *)mixcode;
- (void)dayMixcode:(NSString *)mixcode;
- (void)monthMixcode:(NSString *)mixcode;
- (void)weekOfMonthMixcode:(NSString *)mixcode;
- (void)weekOfYearMixcode:(NSString *)mixcode;
- (void)weekdayMixcode:(NSString *)mixcode;
- (void)nthWeekdayMixcode:(NSString *)mixcode;
- (void)yearMixcode:(NSString *)mixcode;

@end
